# NAME: Sai Siddarth Peta
# Roll Number: CS20B059
# Course: CS3205 Jan. 2023 semester
# Lab number: 2
# Date of submission: 04-03-2023
# I confirm that the source file is entirely written by me without resorting to any dishonest means.
# Website(s) that I used for basic socket programming code are:
# URL(s): None
run:
	python3 lab2-CS20B059.py
clean:
	rm -rf ADS.output NR.output RDS.output TDS.output 