# NAME: Sai Siddarth
# Roll Number: CS20B059
# Course: CS3205 Jan. 2023 semester
# Lab number: 4
# Date of submission: 05-04-2023
# I confirm that the source file is entirely written by me without
# resorting to any dishonest means.
# Website(s) that I used for basic socket programming code are: <NILL>
# URL(s): <NILL> 

client:
		python3 sender.py
server:
		python3 receiver.py