run1:  
	gnome-terminal -- python3 Q1server.py
	gnome-terminal -- python3 Q1client.py
run2:
	gnome-terminal -- python3 Q2server.py
	gnome-terminal -- python3 Q2client.py
run3:
	gnome-terminal -- python3 Q3server.py
	gnome-terminal -- python3 Q3client.py
